### ISSUE TITLE
Can't install clisnips using pip or pipx

### ISSUE THREAD

**Issue by psyray** [ju1ius/clisnips#2]
Hi,

I can't install clisnips using pip or pipx
```
pip install clisnips
ERROR: Could not find a version that satisfies the requirement clisnips (from versions: none)
ERROR: No matching distribution found for clisnips
```
What's the problem ?

**Comment by sgohl** [comment]
same here. Project seems dead. Found any alternatives, somebody? boom etc is not what I'm looking for

**Comment by ju1ius** [comment]
Hey there,

Project's not dead, I'm still using it!
I just didn't have the need (nor the time TBH) to change anything...

pipx supports installing from git urls now:
```sh
pipx install git+https://github.com/ju1ius/clisnips.git
```

I've just pushed some breaking changes though, so you might have to export and reimport your library.

I might even try to publish a release... 🤣 

Cheers!

**Comment by ju1ius** [comment]
FWIW, I just published a stable release and it is now installable from PyPI (at https://pypi.org/project/clisnips)
```sh
pipx install clisnips
```
